apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-endpoint-config
  labels:
    app.kubernetes.io/name: mock-endpoint
    app.kubernetes.io/component: testing
data:
  WAZUH_AGENT_NAME: "mock-endpoint-k8s"
  ATTACK_DELAY: "10"
  ATTACK_INTERVAL: "300"
